---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - image: pyatizbyantsevia/mysql-spring-cs:1.1
        env:
        - name: BD
          value: "jdbc:mysql://172.22.61.155:3306/CourseWork"
        - name: USERNAME
          value: "root"
        - name: PASSWORD
          value: "password"
        name: spring-application
        ports:
        - containerPort: 8080
...