---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - image: pyatizbyantsevia/mysql-spring-cs:1.0
        name: spring-application
        ports:
        - containerPort: 8080
...